import { Place, User } from "../types/api";

export const MOCK_USER: User = {
  _id: "user_123",
  username: "StudentFoodie",
  email: "student@university.edu.ph",
  role: "user",
  favorites: ["place_1", "place_3"],
  contributionCount: 12,
};

export const MOCK_PLACES: Place[] = [
  {
    _id: "place_1",
    name: "Ate Rica's Bacsilog",
    zoneMacro: "Outside",
    zoneMicro: "Gate 3 Side (P. Noval)",
    priceRange: { min: 69, max: 85 },
    amenities: [],
    categories: ["Meryenda", "Rice Meals"],
    coverImage: "https://via.placeholder.com/400x300.png?text=Bacsilog",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    meals: [
      {
        _id: "m1",
        place: "place_1",
        title: "Bacsilog",
        priceRegular: 69,
        isApproved: true,
      },
      {
        _id: "m2",
        place: "place_1",
        title: "Tapsilog",
        priceRegular: 85,
        isApproved: true,
      },
    ],
  },
  {
    _id: "place_2",
    name: "Dimsum Treats",
    zoneMacro: "Inside",
    zoneMicro: "Main Building / Quadricentennial",
    priceRange: { min: 35, max: 60 },
    amenities: ["Aircon"],
    categories: ["Meryenda", "Rice Meals"],
    coverImage: "https://via.placeholder.com/400x300.png?text=Dimsum",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    meals: [
      {
        _id: "m3",
        place: "place_2",
        title: "Siomai Rice",
        priceRegular: 35,
        isApproved: true,
      },
      {
        _id: "m4",
        place: "place_2",
        title: "Wanton Mami",
        priceRegular: 55,
        isApproved: true,
      },
    ],
  },
  {
    _id: "place_3",
    name: "Mang Tootz",
    zoneMacro: "Outside",
    zoneMicro: "P. Noval St.",
    priceRange: { min: 20, max: 150 },
    amenities: [],
    categories: ["Rice Meals", "Meryenda", "Cafe"],
    coverImage: "https://via.placeholder.com/400x300.png?text=MangTootz",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    meals: [
      {
        _id: "m5",
        place: "place_3",
        title: "Banana Rhuma",
        priceRegular: 20,
        isApproved: true,
      },
      {
        _id: "m6",
        place: "place_3",
        title: "Breaded Chicken",
        priceRegular: 95,
        priceHalf: 50,
        isApproved: true,
      },
    ],
  },
  {
    _id: "place_4",
    name: "University Canteen (Carpark)",
    zoneMacro: "Inside",
    zoneMicro: "Carpark 2nd Floor",
    priceRange: { min: 45, max: 80 },
    amenities: ["Wifi", "Charging", "Aircon"],
    categories: ["Rice Meals"],
    coverImage: "https://via.placeholder.com/400x300.png?text=Canteen",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    meals: [
      {
        _id: "m7",
        place: "place_4",
        title: "Pork Adobo",
        priceRegular: 60,
        priceHalf: 40,
        isApproved: true,
      },
      {
        _id: "m8",
        place: "place_4",
        title: "Sinigang",
        priceRegular: 60,
        priceHalf: 40,
        isApproved: true,
      },
    ],
  },
  {
    _id: "place_5",
    name: "7-Eleven",
    zoneMacro: "Outside",
    zoneMicro: "Gate 1 (España)",
    priceRange: { min: 29, max: 150 },
    amenities: ["Aircon", "Charging"],
    categories: ["Meryenda", "Konbini"],
    coverImage: "https://via.placeholder.com/400x300.png?text=7Eleven",
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    meals: [
      {
        _id: "m9",
        place: "place_5",
        title: "Hot Dog",
        priceRegular: 35,
        isApproved: true,
      },
      {
        _id: "m10",
        place: "place_5",
        title: "Sisig Meal",
        priceRegular: 49,
        isApproved: true,
      },
    ],
  },
];
