import { Place } from "../types/Place";
import { User } from "../types/User";

export const MOCK_USER: User = {
  _id: "user_123",
  username: "StudentFoodie",
  email: "student@university.edu.ph",
  role: "user",
  favorites: ["place_1", "place_3"],
  contributionCount: 12,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

// SYNCED WITH SERVER/DATA/MASTERSEED.TS
export const MOCK_PLACES: any[] = [
  {
    _id: "place_1",
    name: "Streetside Lomi Haus",
    zoneMacro: "outside",
    zoneMicro: "Gate 1 Side",
    priceRange: { min: 50, max: 169 },
    amenities: [],
    categories: ["Karinderya", "Meryenda"],
    coverImage:
      "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400",
    status: "active",
    submittedBy: { username: "StudentFoodie" },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    meals: [
      {
        _id: "m1_1",
        place: "place_1",
        title: "4pc Teriyaki Chicken w/ Rice",
        priceRegular: 169,
        isApproved: true,
      },
      {
        _id: "m1_2",
        place: "place_1",
        title: "Spamsilog",
        priceRegular: 89,
        isApproved: true,
      },
      {
        _id: "m1_3",
        place: "place_1",
        title: "Sisigsilog",
        priceRegular: 89,
        isApproved: true,
      },
      {
        _id: "m1_4",
        place: "place_1",
        title: "Lomi Solo",
        priceRegular: 89,
        priceHalf: 50,
        isApproved: true,
      },
    ],
  },
  {
    _id: "place_2",
    name: "Campus Canteen",
    zoneMacro: "inside",
    zoneMicro: "Main Building",
    priceRange: { min: 40, max: 70 },
    amenities: [],
    categories: ["Rice Meals", "Karinderya"],
    coverImage:
      "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400",
    status: "active",
    submittedBy: { username: "StudentFoodie" },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    meals: [
      {
        _id: "m2_1",
        place: "place_2",
        title: "Chicken Adobo",
        priceRegular: 65,
        priceHalf: 40,
        isApproved: true,
      },
      {
        _id: "m2_2",
        place: "place_2",
        title: "Pork Sinigang",
        priceRegular: 70,
        priceHalf: 45,
        isApproved: true,
      },
      {
        _id: "m2_3",
        place: "place_2",
        title: "Lumpia Shanghai",
        priceRegular: 40,
        isApproved: true,
      },
    ],
  },
  {
    _id: "place_3",
    name: "Coffee Bean Café",
    zoneMacro: "inside",
    zoneMicro: "Library",
    priceRange: { min: 85, max: 120 },
    amenities: ["Wifi", "Aircon", "Charging"],
    categories: ["Cafe", "Drinks"],
    coverImage:
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400",
    status: "active",
    submittedBy: { username: "StudentFoodie" },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    meals: [
      {
        _id: "m3_1",
        place: "place_3",
        title: "Iced Caramel Latte",
        priceRegular: 120,
        isApproved: true,
      },
      {
        _id: "m3_2",
        place: "place_3",
        title: "Blueberry Muffin",
        priceRegular: 85,
        isApproved: true,
      },
    ],
  },
  {
    _id: "place_4",
    name: "Burger King Express",
    zoneMacro: "outside",
    zoneMicro: "Gate 2 Side",
    priceRange: { min: 120, max: 180 },
    amenities: ["Aircon", "Wifi"],
    categories: ["Fast Food"],
    coverImage:
      "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400",
    status: "active",
    submittedBy: { username: "StudentFoodie" },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    meals: [
      {
        _id: "m4_1",
        place: "place_4",
        title: "Whopper Meal",
        priceRegular: 180,
        isApproved: true,
      },
      {
        _id: "m4_2",
        place: "place_4",
        title: "Chicken Fries",
        priceRegular: 120,
        isApproved: true,
      },
    ],
  },
  {
    _id: "place_5",
    name: "Tapa King",
    zoneMacro: "outside",
    zoneMicro: "Gate 3 Side",
    priceRange: { min: 90, max: 95 },
    amenities: ["Aircon"],
    categories: ["Rice Meals"],
    coverImage:
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400",
    status: "active",
    submittedBy: { username: "StudentFoodie" },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    meals: [
      {
        _id: "m5_1",
        place: "place_5",
        title: "Tapsilog",
        priceRegular: 95,
        isApproved: true,
      },
      {
        _id: "m5_2",
        place: "place_5",
        title: "Bangsilog",
        priceRegular: 90,
        isApproved: true,
      },
    ],
  },
  {
    _id: "place_6",
    name: "Student Hub Cafeteria",
    zoneMacro: "inside",
    zoneMicro: "Student Center",
    priceRange: { min: 25, max: 50 },
    amenities: ["Wifi", "Aircon", "Charging"],
    categories: ["Karinderya", "Meryenda", "Drinks"],
    coverImage:
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400",
    status: "active",
    submittedBy: { username: "StudentFoodie" },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    meals: [
      {
        _id: "m6_1",
        place: "place_6",
        title: "Pancit Canton",
        priceRegular: 45,
        priceHalf: 25,
        isApproved: true,
      },
      {
        _id: "m6_2",
        place: "place_6",
        title: "Palabok",
        priceRegular: 50,
        priceHalf: 30,
        isApproved: true,
      },
    ],
  },
  {
    _id: "place_7",
    name: "Mang Inasal",
    zoneMacro: "outside",
    zoneMicro: "Gate 1 Side",
    priceRange: { min: 69, max: 159 },
    amenities: ["Aircon"],
    categories: ["Rice Meals", "Unli Rice", "Fast Food"],
    coverImage:
      "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400",
    status: "active",
    submittedBy: { username: "StudentFoodie" },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    meals: [
      {
        _id: "m7_1",
        place: "place_7",
        title: "PM1 (Chicken Inasal)",
        priceRegular: 159,
        isApproved: true,
      },
      {
        _id: "m7_2",
        place: "place_7",
        title: "Halo-Halo",
        priceRegular: 69,
        isApproved: true,
      },
    ],
  },
  {
    _id: "place_8",
    name: "Milk Tea House",
    zoneMacro: "outside",
    zoneMicro: "Gate 3 Side",
    priceRange: { min: 80, max: 90 },
    amenities: ["Aircon", "Wifi"],
    categories: ["Drinks"],
    coverImage:
      "https://images.unsplash.com/photo-1525385444071-b092b93ca120?w=400",
    status: "active",
    submittedBy: { username: "StudentFoodie" },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    meals: [
      {
        _id: "m8_1",
        place: "place_8",
        title: "Classic Milk Tea",
        priceRegular: 80,
        isApproved: true,
      },
      {
        _id: "m8_2",
        place: "place_8",
        title: "Taro Milk Tea",
        priceRegular: 90,
        isApproved: true,
      },
    ],
  },
];
